extends:
  - stylelint-config-recommended

rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - for
      - include
      - mixin
      - use
  no-descending-specificity: null
  unit-no-unknown: null
