- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add nodejs repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x {{ ansible_lsb.codename }} main
    update_cache: yes

- name: Install nodejs
  apt:
    name: nodejs

- name: Install pm2
  npm:
    name: pm2
    global: yes
