name: CD

on:
  release:
    types:
      - published

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build client
        run: yarn run build-client
        env:
          REACT_APP_FRONTEND_ROOT: https://justamouse.com/boardgames
          REACT_APP_SERVER_URL: https://justamouse-boardgames.fly.dev

      - name: Deploy client
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/frontend

  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup fly.io
        run: |
          if ! command -v flyctl >/dev/null; then
            curl -L https://fly.io/install.sh | sh
            echo "${HOME}/.fly/bin" >> "${GITHUB_PATH}"
          fi

      - name: Setup docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${GITHUB_REPOSITORY_OWNER}" --password-stdin && \
          echo "docker_image_name=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}" >> "${GITHUB_ENV}"

      - name: Build server
        run: |
          docker build -t "${docker_image_name}" . && \
          docker push "${docker_image_name}"

      - name: Deploy server
        run: ./infrastructure/fly/flydeploy.sh "${docker_image_name}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          FRONTEND_ROOT: https://justamouse.com
